bug: compiler crashes with an internal error: function is not normal [symbol.cpp:1911]

The full error currently is:
  ./crash1callDestructorsAddon.chpl:79: internal error: function is not normal [symbol.cpp:1911]

NOTE: It is currently skipif'ed for --no-local/etc.
Once this test works for --local, enable it for --no-local and re-test.

Also test it with valgrind.

Prior to r23156, it was failing with an assertion error
[callDestructors.cpp:531] (initially with callDestructors.cpp:256)
- that was due to memory corruption/reusing a freed AST node.

The current failure mode under --no-local --devel is:
$CHPL_HOME/modules/internal/ChapelDistribution.chpl:114: In function 'destroyDom':
$CHPL_HOME/modules/internal/ChapelDistribution.chpl:123: error: SymExpr::var::defPoint is not in AST [expr.cpp:263]


I did not investigate, but seems like it is due to having the same
declaration(s) in the current file *and* in a 'use'-ed module
(see 'use crash1callDestructorsAddon' in the middle of the .chpl file
- the contents of that module duplicate the first half of the .chpl file).
